### ISSUE TITLE
fileHandle.remove is not a function

### ISSUE THREAD

**Issue by steida** [tomayac/opfs-explorer#4]
Can't delete file.

<img width="292" alt="Screenshot 2023-01-30 at 0 55 09" src="https://user-images.githubusercontent.com/66249/215363336-65a2939f-4cea-4d3e-848a-116888a45a8e.png">

**Comment by tomayac** [comment]
The `remove()` method is [supported in Chromium 110](https://chromestatus.com/feature/6318478849998848). Please upgrade your browser to this version. Since _OPFS Explorer_ is a bleeding edge extension and the missing method is shipping anyway, the team decided to not offer a workaround for older versions.
